---

app:
  container_name: app
  build: .
  command: npm start
  ports:
    - "3000:3000"
  links:
    - mysql
mysql:
  container_name: mysql
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: google_map_prototype
    MYSQL_ROOT_PASSWORD: sunday